# Generated by Django 5.1.7 on 2025-03-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=200)),
                ('price_product', models.FloatField()),
                ('srock_product', models.IntegerField()),
            ],
        ),
    ]
